### PR TITLE
Final branch

### PR DESCRIPTION
**Pull request by kayjeee**
In this PR :

 I create an animals table.

 I Insert some animals into the table.

 I create all the necessary queries|
 
 [PIC](https://drive.google.com/file/d/1Jtfq31qNFxh8DToUGzwmfsM6biEHCfZH/view?usp=sharing)
 [PIC 2](https://drive.google.com/file/d/1inCMGzzRYj0n-2x6lLF8x8WkuM2Zv4Fv/view?usp=sharing)
 [PIC 3](https://drive.google.com/file/d/1LjfoxYq8PxCbzKzU8FaUDa5IAZczhpKx/view?usp=sharing)
 [PIC 4](https://drive.google.com/file/d/1SCPMnCUfMBwJqapZ21B0U3QUSDbRjYwi/view?usp=sharing)
 [PIC 5](https://drive.google.com/file/d/1szWa7qhsZQnQ84PVoBxCFLFXh3x4qWT1/view?usp=sharing)
 [PIC 6](https://drive.google.com/file/d/1MD04ae7oC2QYtwMvoQgPmQm5kqmavpah/view?usp=sharing)
 [PIC 7](https://drive.google.com/file/d/1A74NK_H6MnJDSaM0EcuRi8nxyneW4ibA/view?usp=sharing)
 [PIC 8](https://drive.google.com/file/d/1t9r4YCNfZGRP2Ohp4AvBlDkTK4dwZ23M/view?usp=sharing)
 [PIC 9](https://drive.google.com/file/d/1ePmeHbbA1F8I1qJ52n9T0WHSZsULPe9G/view?usp=sharing)

### CODE REVIEW

**Review by BenMukebo — COMMENTED** [review]
## Status: Invalid ❌

### Hi @kayjeee ,
Please fix the issue mentioned below and then request for code review

### Reason
You have submitted a project, that does not have a professional Readme file kindly follow this [microverse template](https://github.com/microverseinc/curriculum-template-databases) and work on your README file by catomizing the readme template then request another review

#### Please make sure to submit code review when you are done with the changes that was requested

**Don't worry you still have same number of requests left as previous.**


Cheers and Happy Coding :clap: :clap: :clap: 

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by kayjeee** [comment]
dear reviewer 
please do not forget to explain how I may add pictures of my screenshot to the pr request

**Review by topeogunleye — COMMENTED** [review]
Hi @kayjeee, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the README file is not complete. Please use the [Microverse template](https://github.com/microverseinc/readme-template).

- [ ] In the case of README consider formatting your README properly like it was formatted in the [Microverse README](https://github.com/microverseinc/readme-template) template as it's a project requirement.

| professional Readme  | Your Readme that is not professional |
| ------------- | ------------- |
|  Recording 2023-02-14 at 12 52 20 (5)	  | image |

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by bobb-Rob — COMMENTED** [review]
Hi @kayjeee, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request


You submitted a project in which the README title and descriptions are not properly written. kindly give the reader a title that reflects the project and a description that provides details as to what the project is about. In the image below, the part labeled `A`, is where the description should be written. Remove all other parts marked with red-X.

image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by KayLemba — APPROVED** [review]
[[# STATUS: APPROVED :green_circle: :clap: 

Hello @kayjeee   , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  . 
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] Professional Readme file 
- [x] No linter errors
- [x] Database working as intended💯 


 

 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



well-1

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]

**Pull request merged**
